CREATE DATABASE cliente_db;

\c cliente_db;

CREATE SEQUENCE public.persona_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

CREATE TABLE public.persona (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	direccion varchar(255) NULL,
	edad int4 NOT NULL,
	genero varchar(255) NULL,
	identificacion varchar(255) NULL,
	nombre varchar(255) NULL,
	telefono varchar(255) NULL,
	CONSTRAINT persona_pkey PRIMARY KEY (id)
);

CREATE TABLE public.cliente (
	"password" varchar(255) NULL,
	id int8 NOT NULL,
	estado bool DEFAULT true NULL,
	CONSTRAINT cliente_pkey PRIMARY KEY (id)
);


ALTER TABLE public.cliente ADD CONSTRAINT fkkpvkbjg32bso6riqge70hwcel FOREIGN KEY (id) REFERENCES public.persona(id);

CREATE DATABASE cuenta_db;

\c cuenta_db;

CREATE SEQUENCE public.movimiento_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

CREATE TABLE public.cliente (
	id int8 NOT NULL,
	"name" varchar(255) NULL,
	identificacion varchar(255) NULL,
	estado bool DEFAULT true NULL,
	CONSTRAINT cliente_pkey PRIMARY KEY (id)
);

CREATE TABLE public.cuenta (
	numero_cuenta varchar(255) NOT NULL,
	cliente_id int8 NULL,
	estado bool NOT NULL,
	saldo_inicial numeric(38, 2) NULL,
	tipo_cuenta varchar(255) NULL,
	CONSTRAINT cuenta_pkey PRIMARY KEY (numero_cuenta)
);

CREATE TABLE public.movimiento (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	fecha date NULL,
	numero_cuenta varchar(255) NULL,
	saldo numeric(38, 2) NULL,
	tipo_movimiento varchar(255) NULL,
	valor numeric(38, 2) NULL,
	saldo_inicial numeric(38, 2) NULL,
	CONSTRAINT movimiento_pkey PRIMARY KEY (id)
);